jdk:
- oraclejdk8
language: java
install: true
cache:
  directories:
  - $HOME/.m2
before_install:
  - cp ./.travis/settings.xml ${HOME}/.m2/settings.xml
script:
  - mvn verify -DskipTests=true -Dmaven.javadoc.skip=true -V
  - mvn site
after_success:
  - bash <(curl -s https://codecov.io/bash)
